/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UuidTO } from '../../uuid-to.model';
import {AuthorTO} from "../../author/api/author-to.model";


export interface BookTO {
    bookId: UuidTO;
    bookName: string;
    mainAuthor: AuthorTO;
}

