/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BookIdTO} from "./book-id-to.model";
import {BookAuthorDescriptionTO} from "./book-author-description-to.model";


export interface BookTO {
    bookId: BookIdTO;
    bookName: string;
    mainAuthor: BookAuthorDescriptionTO;
}

