spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

server:
  error:
    include-message: ALWAYS
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8888
    ssl:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
