spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    embedded:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
    database-platform: org.hibernate.dialect.HSQLDialect
