#minimal setup with lazy initialization to get the chance to replace all facade classes with mocks
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  main:
    lazy-initialization: true
  profiles:
    active: mock


# see https://springdoc.org/#springdoc-openapi-core-properties
springdoc:
  model-converters:
    polymorphic-converter:
      enabled: false
  # add as default application/json and not */* to receive json in angular and not a blob
  default-produces-media-type: application/json
server:
  port: 8081
