package ch.cassiamon.pluginapi.registration.types

import ch.cassiamon.pluginapi.model.ConceptIdentifier

fun interface ConceptReferenceFacetTransformationFunction: FacetTransformationFunction<ConceptIdentifier>
